package com.qeeqez.leetcode.easy;

import java.util.Map;
import java.util.stream.Collectors;

/**
 * 389. Find the Difference
 * <p>
 * You are given two strings s and t.
 * <p>
 * String t is generated by random shuffling string s and then add one more letter at a random position.
 * <p>
 * Return the letter that was added to t.
 */
public class FindTheDifference389 {

    // 100% CPU, 60% MEM - 1 ms
    public char findTheDifference(String s, String t) {
        int charLastCode = 123;
        int[] a = new int[charLastCode];
        int[] b = new int[charLastCode];

        for (char c : s.toCharArray()) {
            a[c]++;
        }

        for (char c : t.toCharArray()) {
            b[c]++;
            if (b[c] > a[c]) return c;
        }

        return 0;
    }

    // 15% CPU, 23% MEM - 10 ms
    public char findTheDifferenceStreamAPI(String s, String t) {
        Map<Character, Integer> letters = s.chars()
                .mapToObj(c -> (char) c)
                .collect(Collectors.toMap(
                        c -> c,
                        c -> 1,
                        Integer::sum
                ));

        return t.chars()
                .mapToObj(c -> (char) c)
                .filter(c -> {
                    Integer count = letters.get(c);
                    if (count == null || count == 0) return true;
                    letters.put(c, count - 1);
                    return false;
                })
                .findFirst()
                .orElseThrow();
    }

}

