services:

  db:
    container_name: leetcode-sql-tests
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: db
      MYSQL_ROOT_PASSWORD: example
    ports:
      - "3500:3306"